#!/usr/bin/python

#Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2
#The first ten pentagonal numbers are:
#1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#It can be seen that P4 + P7 = 22 + 70 = 92 = P8. 
#However, their difference, 70-22 =48 is not pentagonal.
#Find the pair of pentagonal numbers, Pj and Pk, for which their 
#sum and difference is pentagonal and 
#D =abs(Pk-Pj) is minimised; what is the value of D?


def pentagonal( num):
	if ((1 + (1+24*num)**0.5 )/6.0)%1.0 == 0.0:
		return True
	return False

def main():
	i = 2.0;
	notfound = True
	while notfound :
		p1 = ( 3*i**2-i ) /2.0
		for j in range(1,int(i)) :
			p2 = (3*j**2-j)/2.0
			j+=1
			if pentagonal(p1-p2) and pentagonal(p2+p1):
				notfound = False
				print i," ",j," ",p1," ",p2," ",p1-p2
		i+=1.0

if __name__ == '__main__': 
	main()
