#!/usr/bin/python
#
#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
#Pentagonal 	Pn=n(3n-1)/2		1,5,12,22,35,...
#Hexagonal 		Hn=n(2n-1)			1,6,15,28,45
#It can be verified that T285 = P165 = H143 = 40755.
#Find the next triangle number that is also pentagonal and hexagonal.

def istriangle ( num ):
	if ((1+ (1+8*num)**0.5)/2.0 ) %1 == 0:
		return True
	else : 
		return False

def ispentagonal ( num ):
	if (( 1+ (1+24*num)**0.5)/6.0 ) %1 == 0 :
		return True
	else :
		return False

#def ishexagonal ( num):
	

def main():
	n = 2
	idadi = 0
	notFound = True
	while notFound :
		Hn = n*(2*n -1 )
		if ispentagonal (Hn) and istriangle(Hn):
			print Hn
			idadi +=1
			if idadi == 3 :
				notFound = False
			
		n+=1

if __name__ == '__main__' : 
	main()
