
/*
 * Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:
 * Triangle       P3,n=n(n+1)/2     1, 3, 6, 10, 15, ...
 * Square         P4,n=n2           1, 4, 9, 16, 25, ...
 * Pentagonal     P5,n=n(3n−1)/2    1, 5, 12, 22, 35, ...
 * Hexagonal      P6,n=n(2n−1)      1, 6, 15, 28, 45, ...
 * Heptagonal     P7,n=n(5n−3)/2    1, 7, 18, 34, 55, ...
 * Octagonal      P8,n=n(3n−2)      1, 8, 21, 40, 65, ...
 *
 * The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.
 *
 * 1. The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
 * 2. Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.
 * 3. This is the only set of 4-digit numbers with this property.
 *
 * Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type:
 * triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a 
 * different number in the set.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <math.h>

bool triangle(int n){
  float a = (-1 + sqrt( 1+ (8*n)))/2;
  if(ceilf(a)==a){
    return true;
  }
  else return false;
}

bool square (int n){
  float a = sqrt(n);
  if(ceilf(a)==a){
    return true;
  }
  else return false;
}

bool pentagonal (int n){
  float a = (1 + sqrt( 1+ (24*n)))/6;
  if(ceilf(a)==a){
    return true;
  }
  else return false;
}


bool hexagonal (int n){
  float a = (1 + sqrt( 1+(8*n)))/4;
  if(ceilf(a)==a){
    return true;
  }
  else return false;
}

bool heptagonal (int n){
  float a = (3 + sqrt(9 + (40*n)))/10;
  if(ceilf(a)==a){
    return true;
  }
  else return false;
}

bool octagonal (int n){
  float a = (2 + sqrt( 4+ (12*n)))/6;
  if(ceilf(a)==a){
    return true;
  }
  else return false;
}

void test(){
  printf("Triangle: ");
  for(int a=1000; a<10000; a++){
    if(triangle(a)) printf("%d,",a);
  }
  printf("\nSquare: ");
  for(int a=1000; a<10000; a++){
    if(square(a)) printf("%d,",a);
  }
  printf("\nPentagonal: ");
  for(int a=1000; a<10000; a++){
    if(pentagonal(a)) printf("%d,",a);
  }
  printf("\nHexagonal: ");
  for(int a=1000; a<10000; a++){
    if(hexagonal(a)) printf("%d,",a);
  }
  printf("\nHeptagonal: ");
  for(int a=1000; a<10000; a++){
    if(heptagonal(a)) printf("%d,",a);
  }
  printf("\nOctagonals: ");
  for(int a=1000; a<10000; a++){
    if(octagonal(a)) printf("%d,",a);
  }
  printf("\n");
}
int join(int a,int b){
  char sa[10] = "";
  char sb[10] = "";
  sprintf(sa, "%02d", a);
  sprintf(sb, "%02d", b);
  strcat(sa,sb);
  return atoi(sa);
}

int check(int ab){
  int prod = 1;
  if(octagonal(ab)) prod*=13;
  else if(heptagonal(ab)) prod*=11;
  else if(hexagonal(ab)) prod*=7;
  else if(pentagonal(ab)) prod*= 5;
  else if(square(ab)) prod*=3;
  else if(triangle(ab)) prod*=2;
  return prod;
}

void cyclic(){
  int ab,bc,cd,de,ef,fa, total, sum;
  for(int a=10; a<100; a++){
    for(int b=10; b<100; b++){
      ab = join(a,b);
      if(check(ab)==1) continue;
      for(int c=10; c<100; c++){
        bc = join(b,c);
        if(check(bc)==1) continue;
        for(int d=10; d<100; d++){
          cd = join(c,d);
          if(check(cd)==1) continue;
          for(int e=10; e<100; e++){
            de = join(d,e);
            if(check(de)==1) continue;
            for(int f=10; f<100; f++){
              ef = join(e,f); 
              fa = join(f,a);
              if(check(ef)==1 || check(fa)==1) continue;
              total = (check(ab)*check(bc)*check(cd)*check(de)*check(ef)*check(fa));
              if( total%30030 == 0){
                sum = (ab+bc+cd+de+ef+fa);
                printf("S=%d :[%d, %d, %d, %d, %d, %d] -> %d \n",total,ab,bc,cd,de,ef,fa,sum);
                return ;
              }
            }
          }
        }
      }
    }
  }
}

int main(void){
  cyclic();
  //test();

  return 0;
}
